<?php

namespace app\models;

use Yii;

class ClockifyConfigForm extends \yii\base\Model
{
    public $workspaceId;
    public $apiKey;
    public $userId;

    private $owner = Config::OWNER_CLOCKIFY;

    /**
     * @return array
     */
    public function rules()
    {

        return [
            [['workspaceId','apiKey'], 'required'],
            [['workspaceId','apiKey'], 'string'],

            ['userId','integer']

        ];
    }


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $configs = Config::find()->where(['owner' => Config::OWNER_CLOCKIFY, 'userId'=>Yii::$app->user->id])->all();


        foreach ($configs as $item) {
            if ($item->key == 'workspaceId') {
                $this->workspaceId = $item->value;
            }

            if ($item->key == 'apiKey') {
                $this->apiKey = $item->value;
            }
        }
    }

    /**
     * @return Config|bool|null
     * @throws \yii\base\Exception
     */
    public function save()
    {
        $control = Config::find()->where([
            'owner' => Config::OWNER_CLOCKIFY,
            'userId'=>Yii::$app->user->id,
            'key'=>['workspaceId', 'apiKey']
        ])->all();

            if (empty($control) || (count($control) == 0)) {
                return $this->create();
            } else {
                return $this->update();

            }
    }


    /**
     * @return Config|null
     */
    public function create()
    {
        if (!$this->validate()) {
            return null;
        }

        // pt workspace
        $model = new Config();
        $model->owner = $this->owner;
        $model->key = 'workspaceId';
        $model-> value= $this->workspaceId;
        $model->userId = Yii::$app->user->id;
        if (!$model->save()) {
            return null;
        }
        // pt apikey

        $model = new Config();
        $model->owner = $this->owner;
        $model->key = 'apiKey';
        $model-> value= $this->apiKey;
        $model->userId = Yii::$app->user->id;
        if (!$model->save()) {
            return null;
        }

        return $model;
    }

    /**
     * @return bool
     * @throws \yii\base\Exception
     */
    public function update()
    {
        $configs = Config::find()->where(['owner' => Config::OWNER_CLOCKIFY, 'userId'=>Yii::$app->user->id])->all();

        if (empty($configs) || (count($configs) != 2)) {
            throw new \yii\base\Exception('clockify connection keys not found');
        }
        $i = 0;

            foreach ($configs as $item) {
                if ($item->key == 'workspaceId') {
                    $item->value = $this->workspaceId;
                    $item->save();
                    $i++;
                }

                if ($item->key == 'apiKey') {
                    $item->value = $this->apiKey;
                    $item->save();
                    $i++;
                }

            }
            if ($i == 2) return true;
            return false;
    }

}